### PR TITLE
Upgrade to jammy

### PR DESCRIPTION
**Pull request by xnox**
Upgrade to libabigail 2.0 from Ubuntu Jammy (to become 22.04 LTS / the next LTS)

### CODE REVIEW

**Comment by gmelikov** [comment]
Could you please describe what's the purpose of version upgrade?

We're interested to have a minimal version requirement too for local runs.

**Comment by xnox** [comment]
> Could you please describe what's the purpose of version upgrade?
> 
> We're interested to have a minimal version requirement too for local runs.

It's a notification that a new upstream release of libabigail breaks zfs abi checks. Meaning we now have a maximum supported version of 0.8.x.

I am upgrading zfs in development release of Ubuntu jammy / 22.04 which has the new libabigail. The development release of Ubuntu will have a newer libabigail which seems to want different format of abi files and doesn't accept the current ones. Obviously most distributions will pick up the new libabigail soon and would want to build zfs 2.1.1 and/or newer releases. Thus this is a canary notification in a way, that this somehow needs to be resolved. I.e. skipping abi checks if abigail is 2.0 or maintaining two abi files for 0.8 and 2.0; or upgrading the minimum required libabigail to 2.0.

I did this proposal, to preview the zfs change inside a workflow run. (workflow failed redoing it)

I wonder if we need to build & vendor both 0.8 and 2.0 in the docker container, and generate .abi.0.8 and .abi.2.0 files and allow people to verify abi using either abigail 0.8 or 2.0. Or somehow figure out if we can generate universal abi files that are parsed correctly by both abigail 0.8 and 2.0.

**Comment by gmelikov** [comment]
Got it, we already have a minimum version check https://github.com/openzfs/zfs/blob/3eb3e4d14cf008045b79afbbe9d24812d56917be/Makefile.am#L133

Proposed plan:
- update Dockerfile here 
- update CI/ensure to use new image
- push new abi files, our CI generates them on differences https://github.com/openzfs/zfs/actions/runs/1417694022 (see `artifacts`)
- bump version check to 2.0

**Comment by xnox** [comment]
> Got it, we already have a minimum version check https://github.com/openzfs/zfs/blob/3eb3e4d14cf008045b79afbbe9d24812d56917be/Makefile.am#L133
> 
> Proposed plan:
> 
> * update Dockerfile here
> * update CI/ensure to use new image
> * push new abi files, our CI generates them on differences https://github.com/openzfs/zfs/actions/runs/1417694022 (see `artifacts`)
> * bump version check to 2.0

Great! Let me prepare all that then!

**Pull request merged**
